// <auto-generated />
using System;
using Api_demo.Properties.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api_demo.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    partial class EmployeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Api_demo.Properties.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DepartmentCode")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("department");
                });

            modelBuilder.Entity("Api_demo.Properties.Models.Designation", b =>
                {
                    b.Property<int>("DesignationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DesignationName")
                        .HasColumnType("text");

                    b.Property<int?>("departmentId")
                        .HasColumnType("int");

                    b.HasKey("DesignationId");

                    b.HasIndex("departmentId");

                    b.ToTable("designation");
                });

            modelBuilder.Entity("Api_demo.Properties.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("DateOfJoining")
                        .HasColumnType("text");

                    b.Property<int?>("DesignationId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<int?>("departmentId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DesignationId");

                    b.HasIndex("departmentId");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("Api_demo.Properties.Models.Designation", b =>
                {
                    b.HasOne("Api_demo.Properties.Models.Department", "department")
                        .WithMany("designation")
                        .HasForeignKey("departmentId");
                });

            modelBuilder.Entity("Api_demo.Properties.Models.Employee", b =>
                {
                    b.HasOne("Api_demo.Properties.Models.Designation", "designation")
                        .WithMany()
                        .HasForeignKey("DesignationId");

                    b.HasOne("Api_demo.Properties.Models.Department", "department")
                        .WithMany()
                        .HasForeignKey("departmentId");
                });
#pragma warning restore 612, 618
        }
    }
}
